WITH 
  ULTIMAS_LEITURAS AS
  (
    SELECT
      VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO,
      MAX(VDIC_REGISTRO_SINAL_VITAL.CD_COLETA_SINAL_VITAL) CD_ULTIMA_LEITURA
    FROM VDIC_REGISTRO_SINAL_VITAL
    INNER JOIN ATENDIME ON  ATENDIME.CD_ATENDIMENTO = VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO
                            AND ATENDIME.TP_ATENDIMENTO = 'I'
                            AND ATENDIME.DT_ALTA IS NULL
    GROUP BY VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO
  )
  , LEITURAS AS 
  (
      SELECT 
        VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO
        , UNID_INT.CD_UNID_INT
        , UNID_INT.DS_UNID_INT
        , ATENDIME.CD_LEITO
        , LEITO.DS_RESUMO AS DS_LEITO
        , VDIC_REGISTRO_SINAL_VITAL.CD_COLETA_SINAL_VITAL
        , VDIC_REGISTRO_SINAL_VITAL.HORA DT_COLETA
        , VDIC_REGISTRO_SINAL_VITAL.CD_SINAL_VITAL
        , VDIC_REGISTRO_SINAL_VITAL.DS_SINAL_VITAL
        , VDIC_REGISTRO_SINAL_VITAL.VALOR
        , TO_CHAR(ATENDIME.DT_ATENDIMENTO, 'DD/MM/YYYY') || ' ' || TO_CHAR(ATENDIME.HR_ATENDIMENTO, 'HH24:MI:SS') DT_ATENDIMENTO
        , ATENDIME.TP_ATENDIMENTO
        , ATENDIME.CD_CID
      FROM ULTIMAS_LEITURAS
      INNER JOIN VDIC_REGISTRO_SINAL_VITAL ON 
            VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO = ULTIMAS_LEITURAS.CD_ATENDIMENTO
        AND VDIC_REGISTRO_SINAL_VITAL.CD_COLETA_SINAL_VITAL = ULTIMAS_LEITURAS.CD_ULTIMA_LEITURA
      INNER JOIN ATENDIME ON  
            ATENDIME.CD_ATENDIMENTO = VDIC_REGISTRO_SINAL_VITAL.CD_ATENDIMENTO
        AND ATENDIME.TP_ATENDIMENTO = 'I'
        AND ATENDIME.DT_ALTA IS NULL
      INNER JOIN LEITO ON 
            LEITO.CD_LEITO = ATENDIME.CD_LEITO 
        AND LEITO.DT_DESATIVACAO IS NULL
      INNER JOIN UNID_INT ON 
            UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT
      ORDER BY  
          UNID_INT.CD_UNID_INT, 
          ATENDIME.CD_LEITO
  )
  SELECT
    *
  FROM LEITURAS